### PR TITLE
Vet clinic database: database performance audit

### PR DESCRIPTION
**Pull request by Olivier-Kango**
# Vet clinic database: database performance audit

**Hi there 👋**
**In this particular project, @johnkioko and @Olivier-Kango, We:**

1. Make sure that we have our database set up with the schema and data from our previous projects.
2. Run the following query to add an extra column to the owners table:
  ``` sql
  -- Add an email column to your owners table
  ALTER TABLE owners ADD COLUMN email VARCHAR(120);
  ```
email_owners

3. Run the following statements to add data to our database :
  ```sql

  -- This will add 3.594.280 visits considering you have 10 animals, 4 vets, and it will use around ~87.000 timestamps (~4min approx.)
  INSERT INTO visits (animal_id, vet_id, date_of_visit) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hours') visit_timestamp;

  -- This will add 2.500.000 owners with full_name = 'Owner <X>' and email = 'owner_<X>@email.com' (~2min approx.)
  insert into owners (full_name, email) select 'Owner ' || generate_series(1,2500000), 'owner_' || generate_series(1,2500000) || '@mail.com';
  ```
Inert into visits
insert into owners
4 Depening on our machine speed, it might be enough or not. Check that by running `explain analyze SELECT COUNT(*) FROM visits where animal_id = 4`:
     - If you get `Execution time: X ms` and X >= 1000: that should be enough, you can continue to the project requirements.
     - If you get `Execution time: X ms` and X < 1000: please go back to point 3. and repeat until you get a value bigger than 1000ms.

- The following queries are taking too much time (**1 sec = 1000ms can be considered as too much time for database query**). Try them on our machine to confirm it:
  - `SELECT COUNT(*) FROM visits where animal_id = 4;`
animal_id = 4

  - `SELECT * FROM visits where vet_id = 2;`
id - 2

  - `SELECT * FROM owners where email = 'owner_18327@mail.com';`

owners_analyze_snip

- Find a way to decrease the execution time of the first query. Look for hints in the previous lessons.
- Find a way to improve execution time of the other two queries.
- While we are making changes, check if they help by running `EXPLAIN ANALYZE`. Once you succeed, take a screenshot of the `EXPLAIN ANALYZE` result showing that time actually decreased.
- Any changes we made to our database schema is added to the schema.sql file and commited in a new pull request.
- For any `INSERT INTO` queries - we add the to the data.sql file. It is important to keep only the queries that change the database structure in the schema.sql file.
- In our pull request description we include screenshots with `EXPLAIN ANALYZE` results (before and after we improve the speed) for each of the 3 problematic queries.

### CODE REVIEW

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Olivier-Kango, and @johnkioko👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [ ] For the first two queries I can't see the results after the performance audit. Please make sure to add screenshots of results (before and after you improve the speed) for the first two queries as you did for the last query.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olivier-Kango** [comment]
@thecodechaser Kindly would you check again?

**Comment by thecodechaser** [comment]
@Olivier-Kango Please go for another review from your dashboard.

**Review by alexander16108 — APPROVED** [review]
Hi @Olivier-Kango , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olivier-Kango** [comment]
@alexander16108 Thank you

**Pull request merged**
